# Site settings
title: DickvdBrink.github.io
email: dickvdbrink-blog@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. In my post I will talk about C#, TypeScript and maybe some NodeJs
  and ASP.NET. I will also talk about some of my projects and problems I encounter during programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dickvdbrink.github.io" # the base hostname & protocol for your site
github_username:  DickvdBrink

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
